function [data] = clean_datarMMH(data,signal,name,tovalidate,TrialID)
% Clean_data allows to select data from the plot and replace it (by NaN, 0 or [])
% Input data should be nframe * observations

% figure
S.fh = figure('units','normalized',...
    'outerposition',[0.1 0.1 0.8 0.8],...
    'menubar','none',...
    'numbertitle','off',...
    'name',name,...
    'resize','off');
% axes
S.ax = axes('units','normalized',...
    'position',[0.05 0.1 0.8 0.8],...
    'fontsize',8,...
    'nextplot','replacechildren');
S.ax.YLabel.String = data{1}.emgname{1,signal};
% update button
S.but = uicontrol('style','push',...
    'units','normalized',...
    'position',[0.87 0.5 0.1 0.05],...
    'fontsize',14,...
    'string','update',...
    'Callback',{@but_funct,S});

% close button
S.clo = uicontrol('style','push',...
    'units','normalized',...
    'position',[0.87 0.4 0.1 0.05],...
    'fontsize',14,...
    'string','close', ...
    'Callback',@(h,e)closeFig(h,e,S));

    while ishandle(S.fh)
        uiwait(S.fh);
    end
    function but_funct(varargin)
        plot(tovalidate)
		        
        pind = selectdata('selectionmode','Brush');
        pind = pind(end:-1:1);

        pind = find (~cellfun('isempty', pind));
        if ~isempty(pind) 
            for i=1:length(pind)
            data{1,TrialID.trial(pind(i))}.NormRMS(:,signal,TrialID.box(pind(i))) = NaN;
            data{1,TrialID.trial(pind(i))}.Partfemg{1,TrialID.box(pind(i))}(:,signal) = NaN;
            end
        end
        tovalidate(:,pind) = nan;
    end

    function closeFig(varargin) 
        S = varargin{3};
        delete(S.fh)
    end
end